### ISSUE TITLE
Cannot build with webpack

### ISSUE THREAD

**Issue by arthur-s** [kriszyp/alkali-todo#2]
Hello, i pulled this repo; then runned `npm install`, and then `wbpack`.

Cannot build app, this error occurs:

```
artur@book:~/Repositories/alkali-todo$ webpack
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.13.2
Time: 649ms
    + 1 hidden modules

ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/artur/Repositories/alkali-todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:170:20
    at Array.map (native)
    at Function.normalisePlugins (/home/artur/Repositories/alkali-todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/home/artur/Repositories/alkali-todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/home/artur/Repositories/alkali-todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/home/artur/Repositories/alkali-todo/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/artur/Repositories/alkali-todo/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/home/artur/Repositories/alkali-todo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/artur/Repositories/alkali-todo/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/home/artur/Repositories/alkali-todo/node_modules/babel-loader/index.js:131:12)
```

thanks!

**Comment by SergioCrisostomo** [comment]
@arthur-s what is your OS type and node.js version? tried a clean install now and all went good on OSX `10.10.5` and Node.js `v6.2.2`.

**Comment by arthur-s** [comment]
I use Ubuntu, and node js version is `v4.2.1`. Look, i go home (in 3 hours) and try 1) upgrade node 2) or build with broccoli

**Comment by arthur-s** [comment]
@SergioCrisostomo Ok, i tested. First, i tried to build with broccoli, but was errors related to `babel-plugin-transform-alkali`. Finally I upgraded node to latest `v6.6.0` and compiled scrips normally.

**Comment by kriszyp** [comment]
Fascinating, so the babel plugin works with Node v6, but not v4? I am going to give that a try and see if I can reproduce this (would certainly like to have this work on v4).

**Comment by arthur-s** [comment]
I still play with building :) webpack works, but i want to try build it with broccoli, becouse i've been learning it for 1 week. Now when i build it i see an error `Uncaught TypeError: (0 , _alkali.VArray) is not a function`. I'm new to node and to AMD modules, maybe you know why this error raises?

PS. Piece of code in compiled js:

```
define('TodoList', ['exports', 'alkali'], function (exports, _alkali) {

    var TodoList = (0, _alkali.VArray)({  // <---------------- !!! ERROR IS HERE
        // define the default value as an array
        default: [],
        clearCompleted: function () {
            var _this = this;

            // make a copy of the array first, because it changes while we modify it
            this.valueOf().slice(0).forEach(function (todo) {
                if (todo.completed) {
                    _this.delete(todo);
                }
            });
        },

        delete: function (item) {
            this.splice(this.valueOf().indexOf(item), 1);
        }
    });

    exports.default = TodoList;
});
```

**Comment by kriszyp** [comment]
Do you know what the `_alkali` object contains? I wonder if it is compiling the `alkali` module with the return value as the `default` instead of the export object itself.

**Comment by kriszyp** [comment]
If you have a Brocfile.js (is that what you use to configure broccoli?), I could try it out and take a look.

**Comment by arthur-s** [comment]
@kriszyp my fork of yours with Broccoli.js - https://github.com/arthur-s/alkali-todo

UPD. I found very interesting solution, https://github.com/myfreeweb/broccoli-webpack (not tested it, but i belive this module works)

**Comment by kriszyp** [comment]
I tried this out, and it seems that babel's module formatter produces strange output, and seems unable to recognize any existing module (just wraps with AMD, which results in double wrapped AMD modules, which are not usable). I tried switching to using alkali/dist/index.js, but the blind module wrapping doesn't work much better there either. I guess the inability to parse modules is why most people use webpack or something else to do module bundling instead of babel. I am not sure if the transform-amd babel plugin works any better. The broccoli-webpack package does sound like it may be a better solution.
